title = "YBG's Blog"
name = "YBloGeva"
# BaseURL = "http://localhost:1313"
license = "Creative Commons Attribution 4.0 International"
licenselink = "https://creativecommons.org/licenses/by/4.0/"
description = "An excursion into YBG's inner world"
# homepage = "http://46.101.221.201:2015"
tags = ["", "Protocoless", "D2D", "nowall"]
features = ["blog", "gallery"]
canonifyurls = true


[author]
    name = "Yitzhak Bar Geva"

[params]
  Author = "Yitzhakbg"
  DateForm = "Mon, 2 Jan 2006"
  Facebook = "Your ID."
  Twitter = "Your ID."
  Github = "Your ID."
  ShowRelatedPost = true
  Disqus = "Your Disqus."
  SyntaxHighlightTheme = "solarized_dark.min.css"
  sidebartitle = "YBG"
  sidebartagline = "View from inside"
  pygmentsUseClasses = true
  banner = "images/celestial-neighbors-323444.jpg"
  bannerfill = true
  totop = true

[permalinks]
  post = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "About"
    URL = "/about"

[[menu.main]]
    name = "Tech Blog"
    URL = "/tech"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    URL = "http://www.twitter.com/yitzhakbg"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-android'></i>"
    URL = "/about"
    identifier = "ybg"

[[menu.social]]
    pre = "<i class='fa fa-linkedin-square'></i>"
    URL = "https://www.linkedin.com/in/yitzhakbg"
    identifier = "linkedin"

[[menu.footer]]
    name = "Blog"
    URL = "/article"

